In [1]:
import os

In [2]:
from optosplit_functions import process_tiff_folder

input_folder = 'input_tiff_folder'
output_folder_top = 'output_top'
output_folder_bottom = 'output_bottom'

process_tiff_folder(input_folder, output_folder_top, output_folder_bottom)


In [3]:
from optosplit_functions import extract_orb_features

extract_orb_features('output_top', 'output_bottom', 'output_features')

In [4]:
from optosplit_functions import calculate_and_save_homographies

calculate_and_save_homographies('output_features', 'single_homographies')

In [5]:
from optosplit_functions import compute_global_homography

global_homography = compute_global_homography(
    'output_features',  # Replace with your actual folder path containing npz files
    'global_homography.npy'  # Replace with your actual desired output path for the homography matrix
)

In [6]:
import numpy as np

homography_file = 'global_homography.npy'

# Load the homography matrix
homography_matrix = np.load(homography_file)

# Print the homography matrix
print("Homography Matrix:")
print(homography_matrix)

Homography Matrix:
[[ 1.00359885e+00  5.14108487e-03 -3.02713064e+00]
 [-8.63463301e-04  1.00600842e+00  6.66034663e+01]
 [-1.93105783e-07  5.99429111e-06  1.00000000e+00]]


In [ ]:
from optosplit_functions import process_tiff_folder

input_folder = 'test_image'
output_folder_top = 'test_image'
output_folder_bottom = 'test_image'

process_tiff_folder(input_folder, output_folder_top, output_folder_bottom)


In [ ]:
from optosplit_functions import align_and_save_images

align_and_save_images(
    'test_image/10x_001t1_top.png',  # Replace with your actual image path
    'test_image/10x_001t1_bottom.png',  # Replace with your actual image path
    'single_homographies/tile_x003_y002_z004_homography.npy',  # Replace with your actual homography matrix file path
    'test_image'  # Replace with your actual output folder path
)

In [7]:
from optosplit_functions import align_and_save_images

align_and_save_images(
    'test_image/10x_001t1_top.png',  # Replace with your actual image path
    'test_image/10x_001t1_bottom.png',  # Replace with your actual image path
    'global_homography.npy',  # Replace with your actual homography matrix file path
    'test_image'  # Replace with your actual output folder path
)